"""Generate HydroGuard_AI_Forecasting.ipynb (run once from repo root)."""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = Path(__file__).resolve().parent / "HydroGuard_AI_Forecasting.ipynb"

cells = [
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "# HydroGuard AI — Forecasting notebook\n",
            "\n",
            "**Group:** 22409287 A.Z. Zwana · 22442801 A. Tshabalala · 22327842 T. Ngongoma · 22339617 S.S. Mathonsi\n",
            "\n",
            "Four-week Mgeni WSS low-storage forecast for eThekwini (DWS HyData + NASA POWER).\n",
            "\n",
            "Run from the **repository root**:\n",
            "```bash\n",
            "jupyter notebook notebooks/HydroGuard_AI_Forecasting.ipynb\n",
            "```\n",
            "\n",
            "If the processed table is missing:\n",
            "```bash\n",
            "python -m src.build_dataset\n",
            "python -m src.train_model\n",
            "```\n",
        ],
    },
    {
        "cell_type": "code",
        "metadata": {},
        "source": [
            "from pathlib import Path\n",
            "import sys\n",
            "\n",
            "import joblib\n",
            "import pandas as pd\n",
            "import plotly.express as px\n",
            "import plotly.io as pio\n",
            "\n",
            "pio.renderers.default = \"notebook\"\n",
            "\n",
            "ROOT = Path.cwd()\n",
            "if not (ROOT / \"src\").exists():\n",
            "    ROOT = ROOT.parent\n",
            "sys.path.insert(0, str(ROOT))\n",
            "\n",
            "from src.config import DAMS, DEFAULT_LOW_STORAGE_THRESHOLD_PCT, MODELS_DIR, DATA_PROCESSED\n",
            "from src.modelling import coverage_notes, load_modelling_table\n",
            "\n",
            "TABLE_PATH = DATA_PROCESSED / \"weekly_modelling_table.csv\"\n",
            "PIPELINE_PATH = MODELS_DIR / \"pipeline.joblib\"\n",
            "print(\"Project root:\", ROOT)\n",
        ],
        "outputs": [],
        "execution_count": None,
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": ["## 1. Load the cleaned weekly table\n", "\n", "Built by `src/build_dataset.py` from `data/raw/dws/` and `data/raw/nasa_power/`."],
    },
    {
        "cell_type": "code",
        "metadata": {},
        "source": [
            "table = load_modelling_table(TABLE_PATH)\n",
            "coverage = coverage_notes(table)\n",
            "print(f\"Rows: {len(table):,}  |  Labelled weeks: {coverage['n_labelled']}\")\n",
            "print(coverage[\"limitation\"])\n",
            "table.head(8)[[\n",
            "    \"week_start\", \"combined_storage_pct\", \"future_storage_pct\", \"future_low_storage\"\n",
            "]]\n",
        ],
        "outputs": [],
        "execution_count": None,
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "## 2. Data cleaning summary\n",
            "\n",
            "Pipeline in `src/build_dataset.py`:\n",
            "1. Parse DWS HyData Point files; skip invalid; drop duplicate dates\n",
            "2. Convert spillway level → academic storage % (`V = FSC * ((H + level) / H) ** 2`)\n",
            "3. Aggregate to **Monday weeks** (last observation in week per dam)\n",
            "4. Combined % only when all **five dams** observed\n",
            "5. Clean NASA POWER (fill values → NaN); weekly rain sum; catchment mean weather\n",
            "6. Features: lags, rolling rain, season, past-only climatology, dry-week run\n",
            "7. Target: `future_storage_pct` and `future_low_storage` at **t + 4 weeks**\n",
            "\n",
            "**No imputation** of missing dam months.",
        ],
    },
    {
        "cell_type": "code",
        "metadata": {},
        "source": [
            "missing = pd.DataFrame({\n",
            "    \"series\": [f\"{k}_storage_pct\" for k in DAMS] + [\"combined_storage_pct\", \"weekly_rainfall_mm\"],\n",
            "    \"missing_weeks\": [\n",
            "        int(table[c].isna().sum()) if c in table.columns else len(table)\n",
            "        for c in [f\"{k}_storage_pct\" for k in DAMS] + [\"combined_storage_pct\", \"weekly_rainfall_mm\"]\n",
            "    ],\n",
            "})\n",
            "px.bar(missing, x=\"series\", y=\"missing_weeks\", title=\"Missing weeks after cleaning (652 Monday index)\")\n",
        ],
        "outputs": [],
        "execution_count": None,
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": ["## 3. Data visualisation (EDA)\n", "\n", "Same charts as the Streamlit **Exploratory analysis** page."],
    },
    {
        "cell_type": "code",
        "metadata": {},
        "source": [
            "storage = table.dropna(subset=[\"combined_storage_pct\"])\n",
            "fig = px.line(\n",
            "    storage, x=\"week_start\", y=\"combined_storage_pct\", markers=True,\n",
            "    title=f\"Combined Mgeni WSS storage (academic % of 920.90 Mm³)\",\n",
            ")\n",
            "fig.add_hline(y=DEFAULT_LOW_STORAGE_THRESHOLD_PCT, line_dash=\"dash\", annotation_text=\"70% threshold\")\n",
            "fig.show()\n",
        ],
        "outputs": [],
        "execution_count": None,
    },
    {
        "cell_type": "code",
        "metadata": {},
        "source": [
            "dam_cols = [f\"{k}_storage_pct\" for k in DAMS]\n",
            "long = storage.melt(id_vars=[\"week_start\"], value_vars=dam_cols, var_name=\"dam\", value_name=\"storage_pct\")\n",
            "long[\"dam\"] = long[\"dam\"].str.replace(\"_storage_pct\", \"\", regex=False)\n",
            "px.line(long.dropna(subset=[\"storage_pct\"]), x=\"week_start\", y=\"storage_pct\", color=\"dam\",\n",
            "        title=\"Per-dam academic storage %\").show()\n",
        ],
        "outputs": [],
        "execution_count": None,
    },
    {
        "cell_type": "code",
        "metadata": {},
        "source": [
            "rain = table.dropna(subset=[\"weekly_rainfall_mm\"])\n",
            "px.line(rain, x=\"week_start\", y=\"weekly_rainfall_mm\",\n",
            "        title=\"Catchment-mean NASA POWER weekly rainfall\").show()\n",
            "px.box(rain, x=\"season\", y=\"weekly_rainfall_mm\", title=\"Weekly rainfall by season\").show()\n",
        ],
        "outputs": [],
        "execution_count": None,
    },
    {
        "cell_type": "code",
        "metadata": {},
        "source": [
            "labelled = table.dropna(subset=[\"future_low_storage\"])\n",
            "balance = labelled[\"future_low_storage\"].map({0.0: \"Not low in 4w\", 1.0: \"Low in 4w\"}).value_counts().reset_index()\n",
            "balance.columns = [\"class\", \"weeks\"]\n",
            "px.bar(balance, x=\"class\", y=\"weeks\", title=\"Class balance (four-week labels)\").show()\n",
            "\n",
            "cols = [c for c in [\"combined_storage_pct\", \"storage_lag_1w\", \"weekly_rainfall_mm\", \"rain_4w\", \"future_storage_pct\", \"future_low_storage\"] if c in labelled.columns]\n",
            "px.imshow(labelled[cols].corr(), text_auto=\".2f\", title=\"Correlations on labelled weeks\", aspect=\"auto\").show()\n",
        ],
        "outputs": [],
        "execution_count": None,
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": ["## 4. Modelling\n", "\n", "Chronological split: train before 2020-01-01, test after. Metrics from saved `models/metrics.json`."],
    },
    {
        "cell_type": "code",
        "metadata": {},
        "source": [
            "import json\n",
            "metrics_path = MODELS_DIR / \"metrics.json\"\n",
            "if not metrics_path.exists():\n",
            "    raise FileNotFoundError(\"Run: python -m src.train_model\")\n",
            "metrics = json.loads(metrics_path.read_text(encoding=\"utf-8\"))\n",
            "rows = [{\"model\": k, **{m: v.get(m) for m in [\"precision\", \"recall\", \"f1\", \"accuracy\"]}} for k, v in metrics[\"models\"].items()]\n",
            "pd.DataFrame(rows)\n",
        ],
        "outputs": [],
        "execution_count": None,
    },
    {
        "cell_type": "code",
        "metadata": {},
        "source": [
            "bundle = joblib.load(PIPELINE_PATH)\n",
            "primary = metrics[\"models\"][bundle[\"model_type\"]]\n",
            "px.imshow(\n",
            "    primary[\"confusion_matrix\"], text_auto=True,\n",
            "    x=[\"Pred not low\", \"Pred low\"], y=[\"Actual not low\", \"Actual low\"],\n",
            "    title=f\"Test confusion matrix — {bundle['model_type']}\", color_continuous_scale=\"Blues\", aspect=\"equal\",\n",
            ").show()\n",
            "\n",
            "fi = pd.read_csv(MODELS_DIR / \"feature_importance.csv\").sort_values(\"importance\")\n",
            "px.bar(fi, x=\"importance\", y=\"feature\", orientation=\"h\", title=\"Random forest feature importance\").show()\n",
            "metrics.get(\"regression\", {})\n",
        ],
        "outputs": [],
        "execution_count": None,
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": ["## 5. Example four-week forecast\n", "\n", "Uses the saved pipeline (same as Streamlit **Four-week outlook**)."],
    },
    {
        "cell_type": "code",
        "metadata": {},
        "source": [
            "from src.modelling import available_features, matrix, risk_band\n",
            "\n",
            "latest = table.dropna(subset=[\"combined_storage_pct\"]).iloc[-1].copy()\n",
            "latest[\"combined_storage_pct\"] = 65.0  # example: stressed system\n",
            "latest[\"albert_falls_storage_pct\"] = 45.0\n",
            "latest[\"storage_lag_1w\"] = 65.0\n",
            "\n",
            "frame = matrix(pd.DataFrame([latest]), bundle[\"features\"])\n",
            "proba = float(bundle[\"sklearn_pipeline\"].predict_proba(frame)[0, 1])\n",
            "pred_pct = float(bundle[\"regressor\"].predict(frame)[0])\n",
            "print(f\"Low-storage probability: {proba:.1%}\")\n",
            "print(f\"Risk band: {risk_band(proba)}\")\n",
            "print(f\"Ridge future storage %: {pred_pct:.1f}\")\n",
        ],
        "outputs": [],
        "execution_count": None,
    },
]

notebook = {
    "cells": cells,
    "metadata": {
        "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
        "language_info": {"name": "python", "version": "3.13.0"},
    },
    "nbformat": 4,
    "nbformat_minor": 5,
}

OUT.write_text(json.dumps(notebook, indent=1), encoding="utf-8")
print(f"Wrote {OUT}")
